const title = {
    Dash_Board: 'Dashboard',
    Home_Page: 'Trang chủ',
    Product_Page: 'Sản phẩm',
    Detail_Product_Page: 'Chi tiết sản phẩm',
    Sourcing_Page: 'Nghiên cứu sản phẩm',
    Catalogue_Page: 'Catalogue',
    Supplier_Page: 'Quản lý nhà cung cấp',
    Detail_Supplier_Page: 'Chi tiết nhà cung cấp',
    Quote_Sup_Page: 'Quản lý báo giá của nhà cung cấp',
    Buy_Order_Page: 'Đơn hàng mua',
    List_Buy_Order_Page: 'Danh sách đơn hàng mua',
    Add_Buy_Order_Page: 'Mua hàng',
    Detail_Buy_Order_Page: 'Chi tiết đơn hàng mua',
    Customer_Page: 'Quản lý khách hàng',
    Detail_Customer_Page: 'Thông tin chi tiết khách hàng',
    Project_Page: 'Quản lý dự án',
    Detail_Project_Page: 'Chỉ tiết dự án',
    Quote_Cus_Page: 'Báo giá của Wecare',
    Sale_Order_Page: 'Quản lý đơn hàng bán',
    Detail_Sale_Order_Page: 'Chi tiết đơn hàng bán',
    Add_Sale_Order_Page: 'Bán hàng',
    Lot_Management_Page: 'Kế hoạch hàng hóa',
    IO_Management_Page: 'Quản lý xuất nhập',
    Inventory_Management_Page: 'Quản lý kho',
}

export default title;
